/*!
 Copyright [2015] Qualcomm Technologies International, Ltd.
 
 REVISION:      $Revision: #1 $
 */


#import <Foundation/Foundation.h>
#import "CSRRestBaseObject.h"

/*!
 Request Object for secret exchange.
 */

@interface CSRRestExchangeSecretRequest : CSRRestBaseObject

/*!
 UUID of Device
 */
@property(nonatomic) NSString* deviceUUID;

/*!
 MeshID of network
 */
@property(nonatomic) NSString* meshID;

/*!
 A base64 encoded 16 octet random number,  provided by the Gateway.
 */
@property(nonatomic) NSString* authSeed;


/*!
 A base64 encoded 16 octet random number generated by CE.
 */
@property(nonatomic) NSString* authSeed2;

/*!
 Base64 encoded hash, provided by CE.
 */
@property(nonatomic) NSString* ceIdHash;

/*!
 Base64 encoded 80 bit string, used for encryption by configuring entity.
 */
@property(nonatomic) NSString* authSeedResponse;

/*!
 Base64 encoded Message signature, signed by source/configuring entity.
 */
@property(nonatomic) NSString* signature;

/*!
 Base64 encoded diversifier of source/configuring entity.
 */
@property(nonatomic) NSString* diversifier;



-(id)initWithDeviceUUID: (NSString*) deviceUUID
                 meshID: (NSString*) meshID
               authSeed: (NSString*) authSeed
              authSeed2: (NSString*) authSeed2
               ceIdHash: (NSString*) ceIdHash
       authSeedResponse: (NSString*) authSeedResponse
              signature: (NSString*) signature
            diversifier: (NSString*) diversifier;

@end
