//
//  StyleKitName.h
//  
//
//  Created by  on 26/01/2016.
//  Copyright (c) 2016 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKitName : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* watch_light_onTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* watch_lock_closeTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* watch_light_offTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* watch_temp_minusTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* watch_temp_plusTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* watch_lock_close_disabledTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* watch_lock_open_disabledTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* watch_lock_openTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* watch_table_lightTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* watch_table_lockTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* watch_table_heaterTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* watch_table_groupTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* watch_table_sensorTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* watch_connection_lostTargets;

// Drawing Methods
+ (void)drawWatch_light_on;
+ (void)drawWatch_lock_close;
+ (void)drawWatch_light_off;
+ (void)drawWatch_temp_minus;
+ (void)drawWatch_temp_plus;
+ (void)drawWatch_lock_close_disabled;
+ (void)drawWatch_lock_open_disabled;
+ (void)drawWatch_lock_open;
+ (void)drawWatch_table_light;
+ (void)drawWatch_table_lock;
+ (void)drawWatch_table_heater;
+ (void)drawWatch_table_group;
+ (void)drawWatch_table_sensor;
+ (void)drawWatch_connection_lost;

// Generated Images
+ (UIImage*)imageOfWatch_light_on;
+ (UIImage*)imageOfWatch_lock_close;
+ (UIImage*)imageOfWatch_light_off;
+ (UIImage*)imageOfWatch_temp_minus;
+ (UIImage*)imageOfWatch_temp_plus;
+ (UIImage*)imageOfWatch_lock_close_disabled;
+ (UIImage*)imageOfWatch_lock_open_disabled;
+ (UIImage*)imageOfWatch_lock_open;
+ (UIImage*)imageOfWatch_table_light;
+ (UIImage*)imageOfWatch_table_lock;
+ (UIImage*)imageOfWatch_table_heater;
+ (UIImage*)imageOfWatch_table_group;
+ (UIImage*)imageOfWatch_table_sensor;
+ (UIImage*)imageOfWatch_connection_lost;

@end
